import "./globals.css";
import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";

import { Container } from "~/elements/container";
import { Footer } from "~/elements/footer";
import { ThemeSwitchIconButton } from "~/components/theme-switch-button";
import { styled } from "~/styled-system/jsx";

import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"], display: "swap", variable: "--font-body" });
const firaCode = Fira_Code({ subsets: ["latin"], display: "swap", variable: "--font-mono" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html
            lang="en"
            className={`${inter.variable} ${firaCode.variable}`}
            suppressHydrationWarning
        >
            <styled.body w="100vw" h="100vh">
                <Providers>
                    <Container>
                        {children}
                        <Footer>
                            <ThemeSwitchIconButton />
                        </Footer>
                    </Container>
                </Providers>
            </styled.body>
        </html>
    );
}
